assets/index.less
src/Options.jsx
src/Pager.jsx
src/Pagination.jsx

https://github.com/react-component/react-component.github.io
1. prefixCls in js
1. className in js
1. prefixClass in css
1. namespace in css

adjust code style

---

src/Options.jsx
src/Pagination.jsx

This allows specifying the pageSize options dropdown values, which is ortogonal to issue #7.
The default behaviour of the component isn't affected by the PR.

Allow specifying the page size

---

src/locale/en_US.js

For design consistency reasons, I would like to see the forward slash between spaces, not only in front of it.
Currently, this is the way it looks:
And this would be the result of this small change:

items_per_page to include a space

---

src/Pagination.jsx

Hi,
Thank you for open sourcing this. It has helped me greatly.
The html specification states that only an `li` can be a direct child of `ul`.
This matters much more when server rendered and can potentially be causing the `Component's children should not be mutated` in #43.
Thank you
---
Edit: close: https://github.com/react-component/pagination/issues/43

Replace <div> with <li> to follow HTML spec

---

README.md
examples/showTitle.html
examples/showTitle.js
src/Pager.jsx
src/Pagination.jsx
src/locale/zh_TW.js

Because the business needs, do not need to show page title and traditional Chinese internationalization

add showTitle and zh_TW locale

---

package.json

`licenses` has been deprecated and should no longer be used
https://docs.npmjs.com/files/package.json#license

Use "license" for string in package.json

---

.gitignore
package.json
src/Pager.jsx
src/Pagination.jsx
tests/Pagination.spec.js
tests/helper/two-pagination.jsx

**This is a work in progress**, I just wanted to get some feedback if the changes are OK. Then I will add tests and clean up the code.

Make elements keyboard accessible

---

index.js
src/Pagination.jsx
src/index.js

ref: https://github.com/react-component/pagination/pull/83
- remove all Function.protype.bind, use arrow function

refactor: use es6

---

src/Pagination.jsx

it will cause re-render with any keyboardEvent, isn't it ?
You could log in render func, and focus goto input, then press any key to reappear it.

shouldnot always call setState in handleKeyUp func

---

src/locale/nb_NO.js

Adds i18n support for Norwegian Bokmål, one of the official languages in Norway.

Add nb_NO (Norwegian Bokmål) locale

---

src/Pagination.jsx
tests/Pagination.spec.js

This allows passing in `data-*`, `aria-*`, and `role` props to the `<ul>` paginationNode

Pass data-*, aria-*, and role props to paginationNode

---

src/locale/ru_RU.js

Fixed this issue: https://github.com/ant-design/ant-design/issues/11079
`странице` - lexically incorrect for the Russian language in this context. A short form `стр.` is better suited though not ideal.

fix(ru_RU.js): `/ странице` => `/ стр.`

---

src/locale/pt_BR.js

items_per_page means that page is singular, so the translation must be 'página' (singular), not 'páginas' (plural)

Adjust in pt_BR locale

---

package.json
src/Options.jsx
src/Pagination.jsx
tests/Pagination.spec.js

https://github.com/ant-design/ant-design/issues/17763

feat: blur quick jumper input to change current item

---

src/Pagination.jsx

The character used in pagination is changed from '／' to '/'.
The full-width one is only used in some Chinese paragraph.
https://github.com/NG-ZORRO/ng-zorro-antd/pull/4371#discussion_r341892732

fix: replace full-width character with half-width

---

src/locale/en_GB.js
src/locale/en_US.js

English typo correction

---

HISTORY.md
README.md
examples/sizer.js
src/Options.jsx
src/Pagination.jsx
tests/index.test.js

feat: 🆕 size changer will be shown when total >= 100

---

HISTORY.md
README.md
examples/simple.js
examples/sizer.js
src/Options.jsx
src/Pagination.jsx
tests/index.test.js

Improve pagination

---

examples/sizer.js
src/Options.jsx
tests/sizer.test.js

当 `pageSize` 指定了不在默认 `pageSizeOptions` 里面的值时，原来会这样展示。
优化后，会把 `pageSize` 插入到现有的 `pageSizeOptions` 里，符合用户直觉，体验更好。

feat: improve PageSizeOptions with custom pageSize

---

src/Pagination.jsx
tests/sizer.test.js

ref pr: https://github.com/ant-design/ant-design/pull/24514
ref Issue: https://github.com/ant-design/ant-design/issues/24501

fix: change pageSize not call onChange

---

now.json

chore: fix now

---

src/locale/lt_LT.js

Im using antdesign and they have dependencies to pagination version ~2.4.5 but there was no lithuanian language.

added lithuanian language

---

src/Pagination.jsx

Hello! Thanks for creating this library! This fixes an a11y warning I ran into in my application. 
Commit Summary
---- 
This fixes several accessibility warnings related to the jumper caused
by a missing `aria-label`. The fixes can be observed in the
`itemRender` and `jumper` stories in Storybook.
Screenshots
----
|Before | After|
|--|--|
| ![Screen Shot 2020-08-06 at 1 11 35 PM](https://user-images.githubusercontent.com/5473427/89578043-6d095700-d7e6-11ea-8fac-a4318ad9b76e.png) | ![Screen Shot 2020-08-06 at 1 09 44 PM](https://user-images.githubusercontent.com/5473427/89578088-7db9cd00-d7e6-11ea-83d6-5f32600786c1.png) |
| ![Screen Shot 2020-08-06 at 1 11 27 PM](https://user-images.githubusercontent.com/5473427/89578055-71357480-d7e6-11ea-9e87-b152d03322fa.png) | ![Screen Shot 2020-08-06 …

fix: pass label to `getItemIcon` to fix missing `aria-label`

---

src/Options.jsx
tests/jumper.test.js

close https://github.com/ant-design/ant-design/issues/29512
---
之前有个判断 上一页下一页的按钮，但其实点击触发的不是相应的，而是里层的 -item-link。这里修复了下。
增加了 点击 分页的判断，同时这两种情况 都会清空 input 。

fix: click some page & prev btn

---

src/Pager.jsx
src/Pagination.jsx
tests/index.test.js

close https://github.com/ant-design/ant-design/issues/31684

fix: page count should be 1 when total is 0

---

src/Pagination.jsx
tests/index.test.js

- Pagination
- 当 `total` =  0 时，不应该触发 `onChange` 事件。
- https://codesandbox.io/s/ji-ben-antd-4-17-0-alpha-0-forked-lo63f?file=/index.js

fix(Pagination): onChange should be forbidden when total is zero

---

src/Pagination.jsx
tests/jumper.test.js
tests/simple.test.js

handle ant-design 
[#32659](https://github.com/ant-design/ant-design/issues/32659)

feat: simple Pagination cant emit onChange when change page

---

rc-pagination.d.ts

reference https://github.com/ant-design/ant-design/pull/32881#issuecomment-972465196

fix: correct typing of `itemRender`

---

src/locale/si_LK.ts

භාෂාවේ නම: Sinhalese / Sinhala
දේශීය නම: සිංහල
කේතය: සිං / si
`si_LK` is unnecessary but it seems we cannot use `si`

නව භාෂාවක් එකතු කිරීම

---

docs/examples/simple.jsx
src/Pagination.jsx

fix: showTotal should work on simple mode

---

src/locale/ko_KR.js

change locale ko_KR.js items_per_page "/ 쪽" -> "/ 페이지"
"쪽" is not correct

fix: Update ko_KR.js

---

src/Options.tsx

close https://github.com/ant-design/ant-design/issues/42369

fix: use popupMatchSelectWidth instead of dropdownMatchSelectWidth

---

docs/examples/simple.tsx
src/Pagination.tsx
tests/jumper.test.js
tests/simple.test.js

fix https://github.com/ant-design/ant-design/issues/44290

✨ Combination of Simple mode pagination along with page size changer

---

src/Pagination.tsx

fix https://github.com/react-component/pagination/issues/544

fix: remove Array.prototype.at calls

---

docs/examples/align.tsx
docs/examples/basic.tsx
docs/examples/controlled.tsx
docs/examples/itemRender.tsx
docs/examples/jumper.tsx
docs/examples/jumperWithGoButton.tsx
docs/examples/lessPages.tsx
docs/examples/locale.tsx
docs/examples/more.tsx
docs/examples/showSizeChanger.tsx
docs/examples/showTitle.tsx
docs/examples/showTotal.tsx
docs/examples/simple.tsx
docs/examples/sizer.tsx
docs/examples/styles.tsx
docs/examples/utils/commonUtil.tsx
jest.config.js
package.json
src/Options.tsx
src/Options/index.tsx
src/Pagination.tsx
src/interface.ts
tests/__snapshots__/demo.test.tsx.snap
tests/__snapshots__/options.test.tsx.snap
tests/commonUtil.tsx
tests/index.test.tsx
tests/options.test.tsx
tests/simple.test.tsx
tests/sizer.test.tsx
tests/two-pagination.tsx

ref https://github.com/ant-design/ant-design/issues/51961
`selectComponentClass` 耦合太大，基本就是照着 `rc-select` 填的数据。如果是要 `showSizeChanger` 支持 `SelectProps`，那这边就应该直接给个 render 方法。
会发个大版本。

feat: Add `sizeChangerRender` instead of `selectComponentClass`
