react-component/pagination

- assets/index.less
- src/Options.jsx
- src/Pager.jsx
- src/Pagination.jsx
> Merge 1 manually

- examples/jumper.js
- package.json
- src/Options.jsx
- src/Pagination.jsx
select 变成可选依赖，支持传入，不使用就不用打包 select 组件到最终代码
> optional-select

- examples/simple.js
- src/KeyCode.js
- src/Options.jsx
- src/Pagination.jsx
https://github.com/ant-design/ant-design/issues/261
> Some Optimization

- package.json
- tests/Pagination.spec.jsx
- tests/index.spec.js
> Add ui test

- HISTORY.md
- examples/default.html
- examples/default.js
- package.json
- src/Pagination.jsx
- tests/Pagination.spec.jsx
> Add defaultProps.

- src/Pager.jsx
- src/locale/en_US.js
- src/locale/ru_RU.js
- src/locale/zh_CN.js
https://github.com/ant-design/ant-design/issues/2898
> 修复首页、末页title格式化问题

- README.md
- examples/styles.html
- examples/styles.js
- src/Pagination.jsx
> add style support to pagination

- src/locale/cs_CZ.js
Hello,
Can you please merge my pull request? I have added localization for czech language. 
Thank you.
> Czech localization

- src/locale/sk_SK.js
Hi, here is the Slovak translation. Thanks!
> SK Translation

- src/locale/ja_JP.js
I added Japanese locale (`ja_JP`).
> Japanese locale

- src/locale/fi_FI.js
> Add locale fi_FI (#67)

- examples/default.js
- examples/lessPages.js
- examples/more.js
- examples/showTitle.js
- examples/simple.js
- examples/sizer.js
- examples/stupid.js
- examples/styles.js
- package.json
- src/KeyCode.js
- src/Options.jsx
- src/Pager.jsx
- src/Pagination.jsx
- tests/helper/two-pagination.jsx
ref ant-design/ant-design#5678
> Fix prop-types and create-react-class warning

- src/locale/es_ES.js
I added Spanish locale (es_ES).
> Add locale es_ES (Spanish)

- src/Pagination.jsx
- tests/Pagination.spec.js
#61 would not work for this. We believe commit cd4fa10 will. 
(Resolves #78) 
---
Close: https://github.com/react-component/pagination/issues/78
> Accessibility Updates

- src/locale/th_TH.js
resolved #91 
@afc163 Could you merge th_TH to the master branch.
> add th_TH translation

- README.md
- examples/itemRender.html
- examples/itemRender.js
- src/Pager.jsx
- src/Pagination.jsx
- tests/Pagination.spec.js
close https://github.com/react-component/pagination/issues/61 and https://github.com/ant-design/ant-design/issues/6013
> support itemRender

- src/locale/el_GR.js
> Add el_GR locale (Greek)

- src/Pager.jsx
- src/Pagination.jsx
> extract-child-components-to-avoid-binding

- src/locale/pt_PT.js
Hello,
Please add pt_PT locale.
Thanks
> Add pt_PT locale

- src/locale/uk_UA.js
Hello,
Please add Ukrainian locale.
Thanks
> added ukrainian language

- README.md
- src/Pagination.jsx
- tests/Pagination.spec.js
Refer to https://github.com/ant-design/ant-design/pull/8615
> Add hideOnSinglePage props

- src/locale/tr_TR
> Turkish translation

- README.md
- src/Pagination.jsx
- tests/Pagination.spec.js
There is could be needed to hide jump-prev, jump-next items as it is in my project
> Add showPrevNextJumpers props

- src/locale/sl_SI.js
Added slovenian (sl_SI) locale.
Please include it in version.
Thanks.
> added slovenian (sl_SI) locale

- src/Pagination.jsx
- tests/Pagination.spec.js
Fix the issue below:
Once 'total' is 0, 'current' in 'onShowSizeChange' is 0, which is not correct.
> Fix #10524 Pagination issue from Antd

- src/Pagination.jsx
> Remove useless code

- package.json
- rc-pagination.d.ts
> Add typing file

- src/locale/hi_IN.js
Fixes #157 
This PR adds Hindi locale support which can be used by `'rc-pagination/lib/locale/hi_IN'`
> Add Hindi Locale

- src/locale/kn_IN.js
> #13576 - added Kannada locale

- examples/showTotal.js
- src/Pagination.jsx
- tests/Pagination.spec.js
When total is 0, it should display:
not:
> The `from` field in `showTotal` should be 0 when total is 0

- README.md
- assets/index.less
- examples/jumper.js
- now.json
- package.json
- src/Options.jsx
- src/Pagination.jsx
- tests/Pagination.spec.js
ref: https://github.com/ant-design/ant-design/issues/15986
https://rc-pagination-git-disabled.react-component.now.sh/examples/jumper.html
> feat: Support `disabled`

- src/locale/ta_IN.js
> Added Tamil Locale (ta_IN)

- src/locale/pb_IN.js
Hi, Just Added Punjabi (India) locale.
Thanx
> Punjabi (India) locale

- src/Pagination.jsx
Fixed https://github.com/ant-design/ant-design/issues/18985
> fix: improve jump page

- src/Options.jsx
- tests/Pagination.spec.js
Fixed https://github.com/react-component/pagination/issues/206
Fixed https://github.com/ant-design/ant-design/issues/19094
> fix: add check empty string when jumper input trigger blur event

- src/Options.jsx
close https://github.com/ant-design/ant-design/issues/20294
> fix: pagination should not change when click prev/next buttons to blur jumper

- src/Pagination.jsx
- tests/Pagination.spec.js
[#20253](https://github.com/ant-design/ant-design/issues/20523)
> fix: it not work correctly when simple mode and inputing big number;

- .prettierignore
- .prettierrc
- src/locale/az_AZ.js
* Added `.prettierrc` and `.prettierignore` files, since some editors (atom) would format the code with double quotes. 
* Added Azerbaijani locales
> Added prettier config and Azerbaijani locales

- examples/itemRender.js
- src/Pagination.jsx
- tests/Pagination.spec.js
close https://github.com/ant-design/ant-design/issues/21351
> 🆕 pass disabled to custom prev/next item 

- src/locale/ga_IE.js
> 1.x add ga_IE locale

- src/Options.jsx
- src/Pagination.jsx
- tests/index.test.js
- tests/jumper.test.js
> Prev and next button should be a button

- src/Pagination.jsx
related pr https://github.com/ant-design/ant-design/pull/25546   ,   https://github.com/react-component/pagination/pull/272
related issue: https://github.com/ant-design/ant-design/issues/25434
> fix: fire on showsizechange logic

- src/Pager.jsx
related https://github.com/ant-design/ant-design/issues/25627
nofollow links will not influence seo https://support.google.com/webmasters/answer/96569?hl=en
> fix: prevent <a> tag to be crawled

- src/Options.jsx
- https://github.com/ant-design/ant-design/issues/26061
> fix: blur quick jumper

- src/Options.jsx
这个组件并没有current状态（可能某个版本删去了）,对应的逻辑应该重新调整，更符合实际情况。
> fix: fix wrong state

- src/locale/fr_CA.js
Add French(Canada) fr_CA locale
> Feature:Add French(Canada) fr_CA locale

- src/locale/ja_JP.js
Like the Chinese translation, it's proper to add a '件' here.
> Fix the Japanese tranlation of items_per_page.

- src/locale/km_KH.js
> Proofread Khmer translation for km_KH.js

- rc-pagination.d.ts
Add type for `locale` prop.
Close #337
> Add type for `locale` prop.

- docs/index.md
fixed rc-image to rc-pagination
> doc(fix): fix title

- src/locale/eu_ES.js
> Added Basque (eu-ES) translation

- .dumirc.ts
- .gitignore
- package.json
> fix: Don't publish dist to fix Windows install

- package.json
- src/Pagination.tsx
https://github.com/ant-design/ant-design/issues/39900#issuecomment-1565596302
> refactor: use rc-util/lib/pickAttrs

- docs/examples/lessPages.tsx
- src/Options.tsx
- src/Pager.tsx
- src/Pagination.tsx
- src/interface.ts
> chore: code optimization

- src/locale/ne_NP.js
file added src/locale/ne_NP.js
> Internationalization file added for Nepali language

- src/index.ts
> fix: make Type export more convergent

- docs/examples/simple.tsx
- src/Pagination.tsx
- tests/__snapshots__/demo.test.tsx.snap
- tests/__snapshots__/simple.test.tsx.snap
- tests/demo.test.tsx
- tests/simple.test.tsx
fix: https://github.com/ant-design/ant-design/issues/46671
> fix: quick jump render logic
